import type { NextFunction, Request, Response } from 'express';
import { commentService } from '../services/comment.service.js';
import type { CommentRequest } from '../middleware/comment.middleware.js';
import { createCommentSchema, updateCommentSchema } from '../validators/comment.validators.js';
import { emitSocketEvent, organizationRoom, projectRoom, SocketEvent } from '../sockets/socket.events.js';
import { notificationService } from '../services/notification.service.js';

const param = (value: string | string[] | undefined): string => { if (typeof value !== 'string') throw new Error('Invalid route parameter'); return value; };
const context = (request: Request) => request as unknown as CommentRequest;

export const createComment = async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { const value = context(request); const input = createCommentSchema.parse(request.body); const comment = await commentService.create(value.organization._id.toString(), value.user._id.toString(), input); emitSocketEvent(SocketEvent.COMMENT_CREATED, [organizationRoom(value.organization._id.toString()), projectRoom(value.project._id.toString())], comment); const recipients = [...new Set([...input.mentions, value.project.ownerId.toString()])].filter((recipient) => recipient !== value.user._id.toString()); await notificationService.createMany(recipients.map((recipient) => ({ organizationId: value.organization._id.toString(), userId: recipient, projectId: value.project._id.toString(), type: input.mentions.includes(recipient) ? 'MENTION' as const : 'COMMENT' as const, title: input.mentions.includes(recipient) ? 'You were mentioned' : 'New project comment', message: input.content, entityType: input.entityType, entityId: input.entityId, dedupeKey: `comment:${comment._id}:${recipient}` }))); response.status(201).json({ data: comment }); } catch (error) { next(error); } };
export const getComments = async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { response.json({ data: await commentService.list(param(request.params.entityType), param(request.params.entityId)) }); } catch (error) { next(error); } };
export const updateComment = async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { const value = context(request); if (value.comment?.authorId.toString() !== value.user._id.toString()) { response.status(403).json({ error: { message: 'Only the comment author can edit it' } }); return; } const comment = await commentService.update(value.comment, value.organization._id.toString(), updateCommentSchema.parse(request.body)); emitSocketEvent(SocketEvent.COMMENT_UPDATED, [organizationRoom(value.organization._id.toString()), projectRoom(value.project._id.toString())], comment); response.json({ data: comment }); } catch (error) { next(error); } };
export const deleteComment = async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { const value = context(request); if (value.comment?.authorId.toString() !== value.user._id.toString()) { response.status(403).json({ error: { message: 'Only the comment author can delete it' } }); return; } const comment = value.comment; await commentService.delete(comment); emitSocketEvent(SocketEvent.COMMENT_DELETED, [organizationRoom(value.organization._id.toString()), projectRoom(value.project._id.toString())], { _id: comment._id, entityType: comment.entityType, entityId: comment.entityId }); response.status(204).send(); } catch (error) { next(error); } };