import type { NextFunction, Request, Response } from 'express';
import { issueService } from '../services/issue.service.js';
import type { IssueRequest } from '../middleware/issue.middleware.js';
import { createIssueSchema, issueAssigneeSchema, issueCommentSchema, issueLabelsSchema, issuePrioritySchema, issueSeveritySchema, issueStatusSchema, updateIssueSchema } from '../validators/issue.validators.js';
import { emitSocketEvent, issueRoom, organizationRoom, projectRoom, SocketEvent } from '../sockets/socket.events.js';
import { notificationService } from '../services/notification.service.js';
import { createActivityLog } from '../services/activity-log.service.js';

const param = (value: string | string[] | undefined): string => { if (typeof value !== 'string') throw new Error('Invalid route parameter'); return value; };
const query = (value: unknown): string | undefined => typeof value === 'string' ? value : undefined;
const context = (request: Request) => request as unknown as IssueRequest;

export const createIssue = async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { const value = context(request); const issue = await issueService.create(value.organization._id.toString(), value.project._id.toString(), value.user._id.toString(), createIssueSchema.parse(request.body)); await createActivityLog({ organizationId: value.organization._id.toString(), userId: value.user._id.toString(), action: 'ISSUE_CREATED', entityType: 'ISSUE', entityId: issue._id.toString(), description: `Issue ${issue.title} created`, metadata: { projectId: value.project._id.toString() } }); emitSocketEvent(SocketEvent.ISSUE_CREATED, [organizationRoom(value.organization._id.toString()), projectRoom(value.project._id.toString())], issue); response.status(201).json({ data: issue }); } catch (error) { next(error); } };
export const listIssues = async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { const page = Math.max(Number(request.query.page) || 1, 1); const limit = Math.min(Math.max(Number(request.query.limit) || 20, 1), 100); response.json({ data: await issueService.list(param(request.params.projectId), { page, limit, search: query(request.query.search), type: query(request.query.type), status: query(request.query.status), priority: query(request.query.priority), severity: query(request.query.severity), assigneeId: query(request.query.assigneeId), label: query(request.query.label), sprintId: query(request.query.sprintId), sort: query(request.query.sort) ?? '-createdAt' }) }); } catch (error) { next(error); } };
export const getIssue = async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { const value = context(request); response.json({ data: { issue: value.issue, comments: await issueService.comments(value.issue._id.toString()), history: await issueService.history(value.issue._id.toString()) } }); } catch (error) { next(error); } };
export const updateIssue = async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { const value = context(request); const previousAssignee = value.issue.assigneeId?.toString(); const input = updateIssueSchema.parse(request.body); const issue = await issueService.update(value.issue, value.organization._id.toString(), value.user._id.toString(), input); await createActivityLog({ organizationId: value.organization._id.toString(), userId: value.user._id.toString(), action: 'ISSUE_UPDATED', entityType: 'ISSUE', entityId: issue._id.toString(), description: `Issue ${issue.title} updated`, metadata: input }); emitSocketEvent(SocketEvent.ISSUE_UPDATED, [organizationRoom(value.organization._id.toString()), projectRoom(value.project._id.toString()), issueRoom(issue._id.toString())], issue); const assigneeId = issue.assigneeId?.toString(); if (assigneeId && assigneeId !== value.user._id.toString()) await notificationService.notify({ organizationId: value.organization._id.toString(), userId: assigneeId, projectId: value.project._id.toString(), type: previousAssignee !== assigneeId ? 'ISSUE_ASSIGNED' : 'ISSUE_UPDATED', title: previousAssignee !== assigneeId ? 'Issue assigned to you' : 'Issue updated', message: issue.title, entityType: 'ISSUE', entityId: issue._id.toString(), dedupeKey: `issue:${issue._id}:${issue.updatedAt.toISOString()}:${assigneeId}` }); response.json({ data: issue }); } catch (error) { next(error); } };
export const deleteIssue = async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { const value = context(request); const issue = value.issue; await issueService.delete(issue, value.organization._id.toString(), value.user._id.toString()); emitSocketEvent(SocketEvent.ISSUE_DELETED, [organizationRoom(value.organization._id.toString()), projectRoom(value.project._id.toString()), issueRoom(issue._id.toString())], { _id: issue._id, projectId: issue.projectId }); response.status(204).send(); } catch (error) { next(error); } };
const action = (schema: { parse: (value: unknown) => Record<string, unknown> }, field: 'status' | 'priority' | 'severity' | 'assigneeId' | 'labels') => async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { const value = context(request); const data = schema.parse(request.body); const previousAssignee = value.issue.assigneeId?.toString(); const issue = await issueService.action(value.issue, value.organization._id.toString(), value.user._id.toString(), field, data[field]); await createActivityLog({ organizationId: value.organization._id.toString(), userId: value.user._id.toString(), action: field === 'assigneeId' ? 'ISSUE_UPDATED' : 'ISSUE_UPDATED', entityType: 'ISSUE', entityId: issue._id.toString(), description: `Issue ${issue.title} updated`, metadata: { field, value: data[field] } }); emitSocketEvent(SocketEvent.ISSUE_UPDATED, [organizationRoom(value.organization._id.toString()), projectRoom(value.project._id.toString()), issueRoom(issue._id.toString())], issue); const assigneeId = issue.assigneeId?.toString(); if (assigneeId && assigneeId !== value.user._id.toString()) await notificationService.notify({ organizationId: value.organization._id.toString(), userId: assigneeId, projectId: value.project._id.toString(), type: field === 'assigneeId' || previousAssignee !== assigneeId ? 'ISSUE_ASSIGNED' : 'ISSUE_UPDATED', title: field === 'assigneeId' || previousAssignee !== assigneeId ? 'Issue assigned to you' : 'Issue updated', message: issue.title, entityType: 'ISSUE', entityId: issue._id.toString(), dedupeKey: `issue:${issue._id}:${issue.updatedAt.toISOString()}:${assigneeId}` }); response.json({ data: issue }); } catch (error) { next(error); } };
export const changeIssueStatus = action(issueStatusSchema, 'status');
export const changeIssuePriority = action(issuePrioritySchema, 'priority');
export const changeIssueSeverity = action(issueSeveritySchema, 'severity');
export const assignIssue = action(issueAssigneeSchema, 'assigneeId');
export const replaceIssueLabels = action(issueLabelsSchema, 'labels');
export const addIssueComment = async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { const value = context(request); const body = issueCommentSchema.parse(request.body).body; const comment = await issueService.addComment(value.issue, value.organization._id.toString(), value.user._id.toString(), body); emitSocketEvent(SocketEvent.COMMENT_CREATED, [organizationRoom(value.organization._id.toString()), projectRoom(value.project._id.toString()), issueRoom(value.issue._id.toString())], comment); const assigneeId = value.issue.assigneeId?.toString(); if (assigneeId && assigneeId !== value.user._id.toString()) await notificationService.notify({ organizationId: value.organization._id.toString(), userId: assigneeId, projectId: value.project._id.toString(), type: 'COMMENT', title: 'New issue comment', message: body, entityType: 'ISSUE', entityId: value.issue._id.toString(), dedupeKey: `issue-comment:${comment._id}:${assigneeId}` }); response.status(201).json({ data: comment }); } catch (error) { next(error); } };
export const getIssueComments = async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { response.json({ data: await issueService.comments(param(request.params.id)) }); } catch (error) { next(error); } };
export const getIssueHistory = async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { response.json({ data: await issueService.history(param(request.params.id)) }); } catch (error) { next(error); } };