import type { NextFunction, Request, Response } from 'express';
import { issueService } from '../services/issue.service.js';
import type { IssueRequest } from '../middleware/issue.middleware.js';
import { createIssueSchema, issueAssigneeSchema, issueCommentSchema, issueLabelsSchema, issuePrioritySchema, issueSeveritySchema, issueStatusSchema, updateIssueSchema } from '../validators/issue.validators.js';

const param = (value: string | string[] | undefined): string => { if (typeof value !== 'string') throw new Error('Invalid route parameter'); return value; };
const query = (value: unknown): string | undefined => typeof value === 'string' ? value : undefined;
const context = (request: Request) => request as unknown as IssueRequest;

export const createIssue = async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { const value = context(request); response.status(201).json({ data: await issueService.create(value.organization._id.toString(), value.project._id.toString(), value.user._id.toString(), createIssueSchema.parse(request.body)) }); } catch (error) { next(error); } };
export const listIssues = async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { const page = Math.max(Number(request.query.page) || 1, 1); const limit = Math.min(Math.max(Number(request.query.limit) || 20, 1), 100); response.json({ data: await issueService.list(param(request.params.projectId), { page, limit, search: query(request.query.search), type: query(request.query.type), status: query(request.query.status), priority: query(request.query.priority), severity: query(request.query.severity), assigneeId: query(request.query.assigneeId), label: query(request.query.label), sprintId: query(request.query.sprintId), sort: query(request.query.sort) ?? '-createdAt' }) }); } catch (error) { next(error); } };
export const getIssue = async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { const value = context(request); response.json({ data: { issue: value.issue, comments: await issueService.comments(value.issue._id.toString()), history: await issueService.history(value.issue._id.toString()) } }); } catch (error) { next(error); } };
export const updateIssue = async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { const value = context(request); response.json({ data: await issueService.update(value.issue, value.organization._id.toString(), value.user._id.toString(), updateIssueSchema.parse(request.body)) }); } catch (error) { next(error); } };
export const deleteIssue = async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { const value = context(request); await issueService.delete(value.issue, value.organization._id.toString(), value.user._id.toString()); response.status(204).send(); } catch (error) { next(error); } };
const action = (schema: { parse: (value: unknown) => Record<string, unknown> }, field: 'status' | 'priority' | 'severity' | 'assigneeId' | 'labels') => async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { const value = context(request); const data = schema.parse(request.body); response.json({ data: await issueService.action(value.issue, value.organization._id.toString(), value.user._id.toString(), field, data[field]) }); } catch (error) { next(error); } };
export const changeIssueStatus = action(issueStatusSchema, 'status');
export const changeIssuePriority = action(issuePrioritySchema, 'priority');
export const changeIssueSeverity = action(issueSeveritySchema, 'severity');
export const assignIssue = action(issueAssigneeSchema, 'assigneeId');
export const replaceIssueLabels = action(issueLabelsSchema, 'labels');
export const addIssueComment = async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { const value = context(request); response.status(201).json({ data: await issueService.addComment(value.issue, value.organization._id.toString(), value.user._id.toString(), issueCommentSchema.parse(request.body).body) }); } catch (error) { next(error); } };
export const getIssueComments = async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { response.json({ data: await issueService.comments(param(request.params.id)) }); } catch (error) { next(error); } };
export const getIssueHistory = async (request: Request, response: Response, next: NextFunction): Promise<void> => { try { response.json({ data: await issueService.history(param(request.params.id)) }); } catch (error) { next(error); } };