import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiClient } from '../lib/api';
import type { Attachment, AttachmentEntityType } from '../types/attachment';

export const attachmentKeys = { list: (entityType: AttachmentEntityType, entityId: string) => ['attachments', entityType, entityId] as const };
export const useAttachments = (entityType: AttachmentEntityType, entityId: string) => useQuery({ queryKey: attachmentKeys.list(entityType, entityId), queryFn: async () => (await apiClient.get<{ data: Attachment[] }>(`/attachments/${entityType}/${entityId}`)).data.data, enabled: Boolean(entityId) });
export const useUploadAttachment = (entityType: AttachmentEntityType, entityId: string) => { const client = useQueryClient(); return useMutation({ mutationFn: async ({ file, onProgress, targetId }: { file: File; onProgress?: (value: number) => void; targetId?: string }) => { const uploadEntityId = targetId ?? entityId; const form = new FormData(); form.append('file', file); form.append('entityType', entityType); form.append('entityId', uploadEntityId); return (await apiClient.post<{ data: Attachment }>('/attachments', form, { onUploadProgress: (event) => { if (event.total) onProgress?.(Math.round((event.loaded / event.total) * 100)); } })).data.data; }, onSuccess: (_data, variables) => client.invalidateQueries({ queryKey: attachmentKeys.list(entityType, variables.targetId ?? entityId) }) }); };
export const useDeleteAttachment = (entityType: AttachmentEntityType, entityId: string) => { const client = useQueryClient(); return useMutation({ mutationFn: async (id: string) => apiClient.delete(`/attachments/${id}`), onSuccess: () => client.invalidateQueries({ queryKey: attachmentKeys.list(entityType, entityId) }) }); };
export const downloadAttachment = async (id: string, fileName: string): Promise<void> => { const response = await apiClient.get(`/attachments/${id}/download`, { responseType: 'blob' }); const url = URL.createObjectURL(response.data); const anchor = document.createElement('a'); anchor.href = url; anchor.download = fileName; anchor.click(); URL.revokeObjectURL(url); };
export const previewAttachment = async (id: string): Promise<string> => { const response = await apiClient.get(`/attachments/${id}/download`, { responseType: 'blob' }); return URL.createObjectURL(response.data); };