import type { ReactElement } from 'react';
import { useSprintAction, useSprintTaskMutation, useSprint, useDeleteSprint } from '../features/sprints';
import { SprintBurndownChart } from './SprintBurndownChart';
import type { Sprint } from '../types/sprint';

export const SprintDetails = ({ sprint, projectId, availableTasks, onChanged }: { sprint: Sprint; projectId: string; availableTasks: import('../types/task').Task[]; onChanged: () => void }): ReactElement => {
  const details = useSprint(sprint._id); const start = useSprintAction(sprint._id, projectId, 'start'); const complete = useSprintAction(sprint._id, projectId, 'complete'); const remove = useDeleteSprint(sprint._id, projectId); const tasks = useSprintTaskMutation(sprint._id);
  const run = async (action: typeof start) => { await action.mutateAsync(); onChanged(); };
  const metrics = details.data?.metrics;
  const sprintTaskIds = new Set(details.data?.tasks.map((task) => task._id) ?? []);
  return <section className="space-y-5 rounded-xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-cyan-700">{sprint.status}</p><h2 className="text-2xl font-bold text-slate-900">{sprint.name}</h2><p className="text-sm text-slate-500">{sprint.goal || 'No goal set'}</p></div><div className="flex gap-2">{sprint.status === 'PLANNED' && <button className="button max-w-fit" onClick={() => void run(start)}>Start</button>}{sprint.status === 'ACTIVE' && <button className="button max-w-fit" onClick={() => void run(complete)}>Complete</button>}<button className="font-semibold text-red-600" onClick={() => void remove.mutateAsync().then(onChanged)}>Delete</button></div></div>{metrics && <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">Total points</p><strong>{metrics.totalStoryPoints}</strong></div><div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">Completed</p><strong>{metrics.completedStoryPoints}</strong></div><div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">Remaining</p><strong>{metrics.remainingStoryPoints}</strong></div><div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">Completion</p><strong>{metrics.completionPercentage}%</strong></div></div>}{details.data && <><h3 className="font-bold text-slate-900">Sprint burndown</h3><SprintBurndownChart tasks={details.data.tasks} startDate={sprint.startDate} endDate={sprint.endDate} /><h3 className="font-bold text-slate-900">Sprint backlog</h3><ul className="space-y-2">{details.data.tasks.map((task) => <li className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm" key={task._id}><span>{task.title}</span><button className="font-semibold text-red-600" onClick={() => void tasks.mutateAsync({ taskId: task._id, remove: true }).then(onChanged)}>Remove</button></li>)}</ul><h3 className="font-bold text-slate-900">Add tasks</h3><ul className="space-y-2">{availableTasks.filter((task) => !sprintTaskIds.has(task._id)).map((task) => <li className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm" key={task._id}><span>{task.title}</span><button className="font-semibold text-cyan-700" onClick={() => void tasks.mutateAsync({ taskId: task._id }).then(onChanged)}>Add</button></li>)}</ul></>}</section>;
};