import type { ReactElement } from 'react';
import { useState } from 'react';
import { useCreateSprint, useSprints } from '../features/sprints';
import type { Sprint } from '../types/sprint';

export const SprintPlanning = ({ projectId, onSelect }: { projectId: string; onSelect: (sprint: Sprint) => void }): ReactElement => {
  const sprints = useSprints(projectId); const create = useCreateSprint(projectId); const [form, setForm] = useState({ name: '', goal: '', startDate: '', endDate: '' });
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const sprint = await create.mutateAsync(form); onSelect(sprint); setForm({ name: '', goal: '', startDate: '', endDate: '' }); };
  return <section className="space-y-4 rounded-xl bg-white p-5 shadow-sm"><div><h2 className="text-xl font-bold text-slate-900">Sprint planning</h2><p className="text-sm text-slate-500">Plan focused delivery windows for this project.</p></div><form className="grid gap-3 md:grid-cols-2" onSubmit={(event) => void submit(event)}><input className="input" placeholder="Sprint name" required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><input className="input" placeholder="Sprint goal" value={form.goal} onChange={(event) => setForm({ ...form, goal: event.target.value })} /><input className="input" type="date" required value={form.startDate} onChange={(event) => setForm({ ...form, startDate: event.target.value })} /><input className="input" type="date" required value={form.endDate} onChange={(event) => setForm({ ...form, endDate: event.target.value })} /><button className="button max-w-fit" disabled={create.isPending}>Create sprint</button></form><div className="grid gap-3 md:grid-cols-2">{(sprints.data ?? []).map((sprint) => <button key={sprint._id} className="rounded-lg border border-slate-200 p-4 text-left hover:border-cyan-500" onClick={() => onSelect(sprint)}><div className="flex justify-between"><span className="font-bold text-slate-900">{sprint.name}</span><span className="text-xs font-bold text-cyan-700">{sprint.status}</span></div><p className="mt-1 text-sm text-slate-500">{sprint.goal || 'No goal set'}</p></button>)}</div></section>;
};